apiVersion: v1
kind: Secret
metadata:
  name: minio-creds-secret
type: Opaque
data:
  ## Access Key for MinIO Tenant
  accesskey: {{ .Values.tenant.secrets.accessKey }}
  ## Secret Key for MinIO Tenant
  secretkey: {{ .Values.tenant.secrets.secretkey }}