{{ range .Values.tenants }}
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds-secret
type: Opaque
data:
  ## Access Key for MinIO Tenant
  accesskey: {{ .secrets.accessKey }}
  ## Secret Key for MinIO Tenant
  secretkey: {{ .secrets.secretKey }}
{{ end }}
