# Default values for minio-operator.

operator:
  image:
    repository: minio/operator
    tag: v4.0.1
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  replicaCount: 1
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
      ephemeral-storage: 500Mi

console:
  image:
    repository: minio/console
    tag: v0.6.3
    pullPolicy: IfNotPresent
  replicaCount: 1
  secrets:
    passphrase: ThisIsAVeryLongPasswordForExample
    salt: ThisIsAVeryLongPasswordForExample
    accessKey: ThisIsAVeryLongPasswordForExample
    secretKey: ThisIsAVeryLongPasswordForExample

tenant:
  image:
    repository: minio/minio
    tag: RELEASE.2021-03-01T04-20-55Z
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  scheduler: {}
  tolerations: {}
  nodeSelector: {}
  affinity: {}
  resources: {}
  securityContext: {}
  persistence:
    enabled: true
    size: 10Gi
    mountPath: /export
    subPath: /data
  secrets:
    accessKey: ThisIsAVeryLongPasswordForExample
    secretKey: ThisIsAVeryLongPasswordForExample
  metrics:
    enabled: false
    port: 9000
  pools:
    servers: 4
    volumesPerServer: 4
  certificate:
    externalCertSecret: {}
    requestAutoCert: true
    certConfig: {}
    s3:
      bucketDNS: false
  podManagementPolicy: Parallel
  serviceMetadata: {}
  env: {}
  priorityClassName : high-priority